### ISSUE TITLE
what's the meaning of parameter alpha in generator/run.py CONFIG

### ISSUE THREAD

**Issue by XieWenJhin** [HKUST-KnowComp/NeuralSubgraphCounting#4]
what's the meaning of parameter alpha in generator/run.py CONFIG

**Comment by seanliu96** [comment]
As described in Appendix B, 𝛼 ∈ [0, 1] decides the probability of adding subisomorphisms rather than random edges.
In Line 19-22 of Algorithm 2, if a random number is less than 𝛼 , then we will add an isomorphic substructure into g1. Otherwise, we will add a random edge. These parts correspond to Line 465-472 of `generator/graph_generator.py`

**Comment by XieWenJhin** [comment]
Thanks a million!
